"""baseline

Revision ID: b17192f52c8a
Revises: 
Create Date: 2026-09-03 00:16:22.412283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b17192f52c8a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('locality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circuit_external_id'), 'circuit', ['external_id'], unique=True)
    op.create_table('constructor',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nationality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constructor_external_id'), 'constructor', ['external_id'], unique=True)
    op.create_table('driver',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_external_id'), 'driver', ['external_id'], unique=True)
    op.create_table('user',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_table('game',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('invite_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    op.create_index(op.f('ix_game_name'), 'game', ['name'], unique=False)
    op.create_index(op.f('ix_game_season'), 'game', ['season'], unique=False)
    op.create_table('race',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('circuit_id', sa.Uuid(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'round')
    )
    op.create_index(op.f('ix_race_round'), 'race', ['round'], unique=False)
    op.create_index(op.f('ix_race_season'), 'race', ['season'], unique=False)
    op.create_table('f1session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('race_id', sa.Uuid(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'type')
    )
    op.create_index(op.f('ix_f1session_race_id'), 'f1session', ['race_id'], unique=False)
    op.create_table('gameuser',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'user_id')
    )
    op.create_table('prediction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('f1session_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('position_driver_id', sa.Uuid(), nullable=False),
    sa.Column('dnf_driver_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['dnf_driver_id'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['f1session_id'], ['f1session.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['position_driver_id'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'dnf_driver_id', 'f1session_id'),
    sa.UniqueConstraint('game_id', 'position_driver_id', 'f1session_id'),
    sa.UniqueConstraint('game_id', 'user_id', 'f1session_id')
    )
    op.create_table('result',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=False),
    sa.Column('f1session_id', sa.Uuid(), nullable=False),
    sa.Column('constructor_id', sa.Uuid(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('position_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('grid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('laps', sa.Integer(), nullable=True),
    sa.Column('dnf_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructor.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['f1session_id'], ['f1session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id', 'f1session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    op.drop_table('prediction')
    op.drop_table('gameuser')
    op.drop_index(op.f('ix_f1session_race_id'), table_name='f1session')
    op.drop_table('f1session')
    op.drop_index(op.f('ix_race_season'), table_name='race')
    op.drop_index(op.f('ix_race_round'), table_name='race')
    op.drop_table('race')
    op.drop_index(op.f('ix_game_season'), table_name='game')
    op.drop_index(op.f('ix_game_name'), table_name='game')
    op.drop_table('game')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_driver_external_id'), table_name='driver')
    op.drop_table('driver')
    op.drop_index(op.f('ix_constructor_external_id'), table_name='constructor')
    op.drop_table('constructor')
    op.drop_index(op.f('ix_circuit_external_id'), table_name='circuit')
    op.drop_table('circuit')
    # ### end Alembic commands ###
